/* HELM MSP Pricing & tools configuration (single source of truth for the quote tools).
   AUTO-GENERATED by scripts/sync_pricing_sheet.py from the "HELM Licensing & Pricing
   Reference" Google Sheet — do not hand-edit price/tier/tool data here, edit the sheet
   instead and let the sync pick it up (target cadence: every 15-30 minutes). On-site
   cadence logic and this comment block are the only parts NOT sourced from the sheet.
   All prices are exclusive of VAT, per unit/month unless stated. displayName is prospect
   facing (no vendor names).

   Sell prices only — buy costs and margins live in MSP_Pricing.xlsx and never appear here.
   Last synced: 2026-08-24.

   DEVICE ALLOWANCE: every plan includes 2 managed devices per licensed user, covering RMM
   (remote monitoring & management), MDM (mobile device management), and, on any tier where
   EDR is bundled free, EDR too. Devices beyond that allowance are billed monthly per device
   at the rates in HELM_PRICING.tools.rmmOverage / mdmOverage, and, on tiers where EDR is
   bundled free, at the huntressEDR add-on rate. ITDR remains a simple per licensed user
   inclusion with no device allowance.

   BUNDLING MODEL: RMM + MDM (device management) are absorbed into every tier's support fee
   and are never itemised or separately billed within the included allowance. EDR is
   additionally bundled free from Secure upward; ITDR is additionally bundled free from
   Secure+ upward, on a per licensed user basis. Every tool below is also offered as an
   optional, separately priced add-on on the website's Budget Explorer regardless of tier
   (a visitor can add EDR to Essential, or ITDR to Secure, etc.), except any tool flagged
   noBudgetAddon (hidden from the Budget Explorer add-on list but remaining available for
   the invoice matching tool). That's a UI choice made in sectionsC.jsx, not encoded here.

   ON-SITE SUPPORT: cadence scales with headcount and is boosted or trimmed per tier; see
   helmOnsiteLevel below. This is logic, not sheet data, and is carried over unchanged by the
   sync script. Secure's cadence is the base table (11 to 25 users quarterly, 26 to 50
   monthly half day); Essential trims one step below that (remote first); Secure+ adds one
   step above; Enterprise is always weekly/dedicated resource regardless of headcount.

   CONTRACT TERM: every plan starts on a monthly rolling agreement for the client's first 12
   months. Once the client is happy, the agreement renews onto a 36 month term. See the
   footnote surfaced on the site next to the price. */

const HELM_PRICING = {
  support: {
    "Essential":  { sale: 55.00 },
    "Secure":  { sale: 75.00 },
    "Secure+":  { sale: 95.00 },
    "Enterprise":  { sale: 150.00 },
  },
  infra: {
    "Essential":  { sale: 250.00 },
    "Secure":  { sale: 400.00 },
    "Secure+":  { sale: 650.00 },
    "Enterprise":  { sale: 1000.00 },
  },
  tools: {
    huntressEDR:      { displayName: "Endpoint Detection & Response (EDR)", sale: 7.76,  unit: "device" },
    dropsuite:      { displayName: "Email & Cloud Server Backup", sale: 3.92,  unit: "user" },
    huntressITDR:      { displayName: "Identity & Cloud Security Monitoring", sale: 4.14,  unit: "user" },
    exclaimer:      { displayName: "Managed Email Signatures", sale: 1.35,  unit: "user" },
    phin:      { displayName: "Security Awareness Training", sale: 2.50,  unit: "user" },
    egnyteAFS:      { displayName: "File Management & Collaboration", sale: 20.00,  unit: "user", noBudgetAddon: true },
    egnyteIFS:      { displayName: "Advanced File Management & Collaboration", sale: 25.00,  unit: "user", noBudgetAddon: true },
    rmmOverage:      { displayName: "Remote Monitoring & Management (RMM), additional devices", sale: 5.00,  unit: "device", noBudgetAddon: true },
    mdmOverage:      { displayName: "Mobile Device Management (MDM), additional devices", sale: 6.00,  unit: "device", noBudgetAddon: true },
  },
};

/* RMM/MDM is bundled free into every tier's support fee, covering 2 managed devices
   per licensed user. It's rendered as an always-included line rather than living in
   the tools table; devices beyond the allowance are billed via HELM_PRICING.tools
   rmmOverage / mdmOverage, computed in helmBuildTiers. */
const HELM_ALWAYS_INCLUDED = {
  key: 'rmmMdm',
  displayName: 'Device Monitoring, Patching & Management (RMM/MDM)',
  desc: 'Continuous remote monitoring and automated patching of every managed Windows and Mac device, keeping them secure and up to date without interrupting users. Covers 2 managed devices per licensed user; additional devices are billed monthly, shown separately below when they apply.',
};

/* Which HELM_PRICING.tools keys are bundled free into each tier, up to the
   licensed user count. These are shown as included lines on that tier (never
   as a tickable, separately priced add-on there). On any other tier the same
   tool is still a normal optional add-on. Keep in sync with the BUNDLING MODEL
   note above and the invoice tool prompt below. */
const HELM_BUNDLED_BY_TIER = {
  "Essential":  [],
  "Secure":  ["huntressEDR"],
  "Secure+":  ["huntressEDR", "huntressITDR"],
  "Enterprise":  ["huntressEDR", "huntressITDR"],
};

/* Onsite support cadence. A base cadence scales with headcount (the thresholds
   below), then each tier boosts or trims that base by one step, so two clients
   with the same headcount get tier appropriate cadence rather than identical
   cadence everywhere. Secure IS the base table (boost 0). Essential trims one
   step below base, matching its remote first positioning. Secure+ adds one step
   above base. Enterprise always sits at the top level regardless of headcount:
   weekly presence, moving into a dedicated onsite resource conversation, since
   that's part of what Enterprise buys. NOT sourced from the sheet; logic lives
   here only, edit this script's TEMPLATE to change it. */
const HELM_ONSITE_LEVELS = [
  { level: 0, label: 'Onsite Support', sub: 'Remote first · ad hoc onsite visits billed separately',
    desc: 'No scheduled onsite visits. Your team is supported remotely day to day; an onsite visit can be arranged and billed separately whenever it is needed.' },
  { level: 1, label: 'Onsite Support', sub: 'Quarterly visit, half day',
    desc: 'A scheduled half day onsite visit every quarter, for hands on work, stakeholder check ins and anything easier to resolve in person.' },
  { level: 2, label: 'Onsite Support', sub: 'Monthly visit, half day',
    desc: 'A scheduled half day onsite visit every month, keeping a regular in person cadence alongside remote support.' },
  { level: 3, label: 'Onsite Support', sub: 'Monthly visit, full day (or fortnightly half day)',
    desc: 'A scheduled full day onsite visit every month, or a half day visit every fortnight, whichever suits your team\u2019s working pattern.' },
  { level: 4, label: 'Onsite Support', sub: 'Weekly onsite presence',
    desc: 'Weekly onsite presence as standard. At this scale a dedicated part time or full time onsite resource is usually the more cost effective option compared with ad hoc visits; we\u2019ll scope that as part of onboarding.' },
];

function helmOnsiteLevel(tier, users) {
  if (tier === 'Enterprise') return HELM_ONSITE_LEVELS[4];
  let base = 0;
  if (users > 100) base = 4;
  else if (users > 50) base = 3;
  else if (users > 25) base = 2;
  else if (users > 10) base = 1;
  const boost = tier === 'Secure+' ? 1 : tier === 'Essential' ? -1 : 0; // Secure = 0 (base table)
  const lvl = Math.max(0, Math.min(4, base + boost));
  return HELM_ONSITE_LEVELS[lvl];
}

/* Support hours model: AI triage and remediation runs 24/7 on every plan (see
   sectionsC.jsx), regardless of tier, so a client can always get hold of HELM.
   "hours" below is when a live human engineer is covering at no extra charge;
   fullCover marks the tiers where that live cover is truly 24/7/365. Outside
   the stated hours on a non fullCover tier, a client can still reach a human
   engineer; it's just billed hourly rather than included. Only Secure+ and
   Enterprise are fullCover, with no hourly billing for out of hours access to
   a human engineer. */
const HELM_SLA = {
  "Essential":  { hours: "Live team 08:00 to 18:00 Monday to Friday", fullCover: false, reporting: "Quarterly" },
  "Secure":  { hours: "Live team 07:00 to 20:00 Monday to Friday", fullCover: false, reporting: "Monthly" },
  "Secure+":  { hours: "Live team 24/7/365", fullCover: true, reporting: "Monthly" },
  "Enterprise":  { hours: "Live team 24/7/365", fullCover: true, reporting: "Weekly" },
};

const HELM_DESCRIPTORS = {
  huntressEDR:      "Endpoint Detection & Response goes beyond antivirus, continuously hunting for attacker behaviour, fileless threats and post exploitation activity that AV cannot see. Backed by a 24/7 Security Operations Centre. Included free of charge on Secure and above, and shown here as an optional upgrade for Essential. Covers 2 managed devices per licensed user on tiers where it is bundled free; additional devices are billed monthly, shown separately below when they apply.",
  dropsuite:      "Automated daily backup of all Microsoft 365 and Google Workspace data: email, calendars, contacts and cloud files. Point in time restore to any date.",
  huntressITDR:      "Monitors your Microsoft 365 or Google Workspace identity layer for suspicious logins, privilege escalation and account compromise, catching threats cloud AV cannot see. Included free of charge on Secure+, and shown here as an optional upgrade for Essential and Secure.",
  exclaimer:      "Centrally managed, consistent email signatures across the whole organisation. Brand compliant on every device, every email client.",
  phin:      "Continuous phishing simulation and bite sized security training that builds staff awareness and measurably reduces human risk.",
  egnyteAFS:      "Secure cloud file management and collaboration platform, giving your team fast, controlled access to business files from any device, with full audit trails and admin oversight.",
  egnyteIFS:      "Everything in File Management & Collaboration plus intelligent content classification, advanced ransomware detection and deeper compliance controls for larger, more sensitive file estates.",
  rmmOverage:      "Additional remote monitoring and management coverage for managed devices beyond your plan's included allowance of 2 devices per licensed user.",
  mdmOverage:      "Additional mobile device management coverage for managed devices beyond your plan's included allowance of 2 devices per licensed user.",
};

const HELM_TIER_NAMES = ["Essential", "Secure", "Secure+", "Enterprise"];

function helmRecommendTier(userCount) {
  if (userCount > 100) return "Enterprise";
  if (userCount > 25) return "Secure+";
  if (userCount > 10) return "Secure";
  return "Essential";
}

/* Prompt used by the AI invoice-comparison tool. Prices mirror the config above,
   generated from the same sheet data so the two can never drift apart. */
const HELM_QUOTE_CONTEXT = `You are a quoting assistant for HELM, a global IT consultancy. A prospective client has shared their current IT invoice so HELM can produce a comparable quote.

SUPPORT TIERS (per user/mo): Essential £55 | Secure £75 | Secure+ £95 | Enterprise £150
INFRASTRUCTURE FEE (flat per client/mo): Essential £250 | Secure £400 | Secure+ £650 | Enterprise £1,000

BUNDLED IN EVERY TIER (never a separate line item, never billed, do not add to helm_mapping or helm_total): Windows/Mac device monitoring, patching and management (RMM/MDM), covering 2 managed devices per licensed user. This replaces any "RMM", "NinjaOne", "Addigy", "device management" or "patch management" line on the customer's invoice: map it to nothing and mention in notes that it's included at no extra cost. If the invoice states a device count more than double the user count, note the likely RMM/MDM overage (£5/device for RMM, £6/device for MDM, beyond the 2 per user allowance) in notes, but do not add it to helm_mapping or helm_total unless the invoice gives you a device count to calculate from.

ALSO BUNDLED FREE from Secure upward (never billed on Secure/Secure+/Enterprise quotes, only shown as a paid add-on when quoting Essential): Endpoint Detection & Response (EDR), covering 2 managed devices per licensed user; devices beyond that allowance are billed at the EDR add-on rate below. Matches any "EDR", "SentinelOne", "CrowdStrike", "advanced antivirus" or similar line on the customer's invoice.
ALSO BUNDLED FREE from Secure+ upward (never billed on Secure+/Enterprise quotes, only shown as a paid add-on when quoting Essential or Secure): Identity & Cloud Security Monitoring (ITDR), per licensed user with no device allowance. Matches any "identity protection", "ITDR" or "M365 security monitoring" line.

PAID ADD-ONS (per device or user/mo; every add-on below is available on EVERY tier, including a tier where the same tool is already bundled free; never add a bundled-free tool as a paid add-on on the tier that bundles it): Endpoint Detection & Response (EDR) £7.76/device | Email & Cloud Server Backup £3.92/user | Identity & Cloud Security Monitoring (ITDR) £4.14/user, Microsoft 365 or Google Workspace | Managed Email Signatures £1.35/user | Security Awareness Training £2.50/user | File Management & Collaboration (Egnyte AFS) £20.00/user | Advanced File Management & Collaboration (Egnyte IFS) £25.00/user

MICROSOFT 365 LICENCES (per user/mo): M365 Business Basic £6.00 | M365 Business Standard £13.50 | M365 Business Premium £24.00 | M365 Apps for Business £9.72 | M365 E3 (no Teams) £34.80 | M365 E5 (no Teams) £56.52 | Microsoft Teams Essentials £3.72 | Microsoft Teams Enterprise £7.92 | Microsoft Teams Rooms Pro £36.96 | Microsoft Entra ID P1 £5.88 | Microsoft Power BI Pro £12.96 | Microsoft Project Plan 3 £29.64 | Microsoft Visio Plan 2 £13.80 | Exchange Online Plan 1 £3.96 | Exchange Online Plan 2 £7.92 | O365 Enterprise E3 (legacy) £26.40
GOOGLE WORKSPACE LICENCES (per user/mo): Google Workspace Business Starter £7.00 | Google Workspace Business Standard £13.00 | Google Workspace Business Plus £24.00 | Google Workspace Enterprise Plus £35.30 | GWS Enterprise Plus Archived User £7.00 | Google Workspace Business Plus Archive £4.00

RULES FOR CHOOSING THE TIER (read carefully, this is the most important part):
1. First find the headcount implied tier: Essential up to 10 users, Secure 11 to 25, Secure+ 26 to 100, Enterprise 100+. Treat this only as a starting point, never as the final answer.
2. Do not default straight to the headcount implied tier. Every add-on above is available on every tier, so a cheaper tier plus only the specific paid add-ons needed to replicate what the customer's invoice already shows them paying for can easily beat a pricier tier that happens to bundle one of those same tools in for free. The per-user fee step between tiers is usually bigger than the cost of the individual add-on(s) it bundles. Example: a 30 user prospect whose invoice shows support at £65/user plus EDR billed separately. Secure+ (£95/user) bundles EDR free, but Essential (£55/user) + the EDR add-on (£7.76/device) comes to about £62.76/user: cheaper than Secure+, and cheaper than their current £65 plus EDR too. Do not jump straight to the tier EDR happens to be bundled on; check the maths.
3. Concretely: for every tier from Essential up to the headcount implied tier, work out the full monthly cost of matching everything on the invoice at that tier: support fee × users, plus the infrastructure fee, plus a paid add-on for anything that tier does not bundle free but the invoice shows the customer already has. Recommend whichever tier gives the lowest total monthly cost.
4. Any mention on the invoice of 24/7 user support, 24/7 helpdesk, round the clock support, out of hours support, weekend cover, or similar language always triggers a recommendation of at least Secure+, the lowest tier with a human engineer included 24/7/365 at no extra charge (Essential and Secure only offer a human engineer out of hours on a billed hourly basis). When this applies, skip the cost comparison in rules 2 and 3 entirely: recommend Secure+, or Enterprise if the headcount implied tier from rule 1 is already Enterprise, regardless of whether a cheaper tier could otherwise match the rest of the invoice, and say in notes that the invoice specifies 24/7 support and only Secure+ and Enterprise deliver that at no extra charge. If the invoice does not mention 24/7 support or similar in any form, ignore this rule and follow rules 2 and 3 as normal. Never infer a 24/7 requirement purely from headcount or company size.
5. If the cheapest tier and the headcount implied tier land within a few pounds a month of each other, prefer the headcount implied tier: its support hours and onsite cadence are better for a negligible cost difference, and say so in notes.
6. Once you've picked the tier: match every remaining line item on the invoice to the closest HELM equivalent, applying the bundling rules above. Include that tier's support fee and infrastructure fee. Use exact HELM sale prices only for these direct matches. monthly_price = per-unit price only, never a line total. For any invoice line with no direct HELM equivalent, still add it to helm_mapping so the client is quoted for it: helm_equivalent = a short label for it (drawn from the invoice), unit = "flat", monthly_price = exactly the price already shown on the invoice for that line — never invent a figure. If the invoice gives no price for that line, leave it out of helm_mapping and helm_total entirely. Also add a short label for every such item to unmatched_items, so it's still called out separately as something the team will confirm — this is for the sales rep's benefit only and must never be double counted. helm_total = sum of all (qty x monthly_price) across every line in helm_mapping, including paid add-ons and items priced this way, excluding anything bundled free at that tier.
7. In notes, write one short sentence (no more than about 20 words) naming the tier and the single clearest reason, in plain English a sales rep can read straight off the screen — for example "Essential — your invoice doesn't mention 24/7 support, so a cheaper tier covers everything you have." or "Secure+ — your invoice specifies 24/7 support, which only Secure+ and Enterprise include at no extra charge." Do not walk through the cost comparison, list every tier considered, or mention specific pound figures — just the headline reason.

Return ONLY a valid JSON object, no explanation or text outside the JSON:
{"users":<number>,"devices":<number>,"tier":"<Essential|Secure|Secure+|Enterprise>","helm_mapping":[{"helm_equivalent":"string","qty":<number>,"unit":"<user|device|flat>","monthly_price":<per-unit price>}],"helm_total":<number>,"unmatched_items":["string"],"notes":"string"}`;

Object.assign(window, { HELM_PRICING, HELM_SLA, HELM_DESCRIPTORS, HELM_TIER_NAMES, HELM_ALWAYS_INCLUDED, HELM_BUNDLED_BY_TIER, HELM_ONSITE_LEVELS, helmOnsiteLevel, helmRecommendTier, HELM_QUOTE_CONTEXT });
